Feature/crop
HASH-SQUAD/Harp-Web pull request #81
Opened 2024-08-17 12:47 UTC by rkdalswl718

### 📌 개요
프로필 사진, 계획 소개 사진 선택시 이미지 크롭 하는 기능을 개발했습니다.

#### 🔗 작업 내용
1. react-easy-crop 라이브러리 사용
2. 사진 선택 후 자른 사진으로 처리

#### 🐳 반영 브랜치
feature/crop -> devleop

#### 🕶️ 테스트 결과
https://github.com/user-attachments/assets/711c1a50-254e-4b8b-91ba-d47f3b9031be

#### 🔅 기타

2024-08-17 17:24 UTC, chooseongwoo requested changes

2024-08-17 17:24 UTC, chooseongwoo commented on src/components/ImageUpload/index.tsx
> +const ImageUpload: React.FC<ImageUploadProps> = ({ onImageSelect }) => {
```suggestion
const ImageUpload = ({ onImageSelect }: ImageUploadProps) => {

```
React.FC 사용을 지양해주세요.
그리고 이 컴포넌트는 시연영상에서 보이지 않는 것 같은데 어디서 사용되는 것인가요?

2024-08-17 17:41 UTC, Jamkris reviewed
수정해주세요!

2024-08-17 17:41 UTC, Jamkris commented on src/lib/utils/cropImage.ts
> +    }, 'image/jpeg');
여기서 추가로 filetype을 지정할 수 있는데 png,jpg,jpeg의 파일타입을 지정해서 올릴 수 있도록 해주세요.

2024-08-17 17:41 UTC, Jamkris commented on src/lib/utils/cropImage.ts
> +    image.addEventListener('error', (error) => reject(error));
여기에 `image.setAttribute('crossOrigin', 'anonymous');` 추가해서 CORS 오리진 에러가 나지 않도록 해주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/CropImage/index.tsx
> +  };
useCallback을 사용해서 불필요한 리렌더링을 없애주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/CropImage/index.tsx
> +  };
useCallback을 사용해서 불필요한 리렌더링을 없애주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/CropImage/index.tsx
> +          onCropComplete(croppedImage);
`onCropComplete?.(croppedImage);`로 수정해서 onCropComplete 함수가 존재할 때만 호출하도록 변경해주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/ImageCrop/index.tsx
> +  };
useCallback을 사용해서 불필요한 리렌더링을 없애주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/ImageCrop/index.tsx
> +  };
useCallback을 사용해서 불필요한 리렌더링을 없애주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/ImageCrop/index.tsx
> +          onCropComplete(croppedImage);
onCropComplete?.(croppedImage);로 수정해서 onCropComplete 함수가 존재할 때만 호출하도록 변경해주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/ImageUpload/index.tsx
> +  };
useCallback을 사용해서 불필요한 리렌더링을 없애주세요.

2024-08-17 17:58 UTC, Jamkris commented on src/components/ImageUpload/index.tsx
> +      const file = e.target.files && e.target.files[0];
` const file = target.files?.[0];` 이 방식으로 처해해서 안정성을 높여주세요 만약 파일이 지원되지 않을 경우 오류를 발생시킬 수 있습니다.

2024-08-17 17:58 UTC, Jamkris commented on src/components/ImageUpload/index.tsx
> +        };
```suggestion
reader.onload = (event: ProgressEvent<FileReader>) => {
          const result = event.target?.result;
          if (typeof result === 'string') {
            onImageSelect(result);
          }
        };
```

이런식으로 이벤트 타입을 명시적으로 사용해서 안정성을 높일 수 있습니다.
&
타입이 string일 경우에만 `onImageSelect`함수를 호출 할 수 있도록 해주세요.

2024-08-17 17:59 UTC, Jamkris commented on src/lib/utils/handleImageEdit.ts
> +//src/lib/utils/handleImageEdit.ts
GPT의 흔적

2024-08-17 18:18 UTC, chooseongwoo commented on src/pages/profile/crop/style.ts
> +`;
```
width: 100%;
```
지정해주세요.

2024-08-17 18:18 UTC, chooseongwoo commented on src/pages/profile/edit/index.tsx
> +
```suggestion
  useEffect(() => {
    const croppedImage = location.state?.croppedImage;
    if (croppedImage) {
      setProfileImage(croppedImage);
      setIsChanged(true);
    }
  }, [location.state?.croppedImage]);

```

가독성 향상을 위해 이렇게 해보는건 어떨까요

2024-08-20 23:19 UTC, chooseongwoo approved these changes
수고하셨습니다.

2024-08-20 23:19 UTC, merged